build:
    nodes:
        tests:
            environment:
                java: 'java-8-oracle'
                timezone: Europe/Paris

            services:
                mysql: 5.7

            tests:
                override:
                    - command: mysql -u root -e "create database araknemu"
                    - command: mysql -u root -e "create user araknemu"
                    - command: mysql -u root -e "grant all privileges on araknemu.* to araknemu"
                    - command: mvn test
                      coverage:
                        file: 'target/site/jacoco/jacoco.xml'
                        format: 'jacoco'
